[project]
name = "relicapgrid"
version = "0.1.0"
description = "Synthetic grid model for ENTSO-E Regional Coordination Processes data exchange use cases"
readme = ".github/README.md"
authors = [
    { name = "Eduardo RelAlg" },
    { name = "Haris Vranaj" },
    { name = "Svein Harald Olsen" },
    { name = "Kristjan Vilgo" },
    { name = "Thomas Viegut" },
    { name = "Faris Malicevic" },
    { name = "Lars Truelsen" },
    { name = "Holdersen" },
    { name = "Decodre" },
    { name = "Bence Szirbik" },
    { name = "Benedek Fodor" },
    { name = "Jakub" },
    { name = "Philip Weaver" },
    { name = "Sindre VH" },
    { name = "emhg23" },
    { name = "Daria" },
    { name = "Pavel Kocica" },
    { name = "Makkes" }
]
license = "CC-BY-SA-4.0"
requires-python = ">=3.12"
dependencies = [
    "pandas",
    "triplets[polars,oxigraph,validation]==0.2.0",
    "pytest",
    "tabulate>=0.10.0",
]

[project.urls]
Homepage = "https://github.com/entsoe/relicapgrid"
Repository = "https://github.com/entsoe/relicapgrid"
Issues = "https://github.com/entsoe/relicapgrid/issues"


[tool.uv]
package = false

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["buildScripts"]
addopts = "--tb=short --no-header -v"

[build-system]
requires = ["uv_build>=0.11.8,<0.12.0"]
build-backend = "uv_build"
